services:
  - type: web
    name: oftalmo-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      # Crear superusuario si no existe
      echo "from django.contrib.auth import get_user_model; User=get_user_model(); \
      User.objects.filter(username='admin').exists() or \
      User.objects.create_superuser('admin','admin@example.com','admin123')" | python manage.py shell
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
