# Generated by Django 3.2.25 on 2025-08-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='clase_servicio',
            field=models.CharField(choices=[('CONS', 'Consulta'), ('URG', 'Urgencias'), ('HOSP', 'Hospitalización'), ('MED', 'Medicamentos')], default='CONS', max_length=10, verbose_name='Clase de Servicio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ingreso_salarios_minimos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se calcula automáticamente según el nivel, nivel 4 si ingresos >6 SM', max_digits=10, null=True, verbose_name='Ingreso aproximado (SM)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nivel',
            field=models.CharField(blank=True, choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4')], max_length=1, null=True, verbose_name='Nivel de ingresos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='regimen',
            field=models.CharField(blank=True, choices=[('C', 'Contributivo'), ('S', 'Subsidiado'), ('E', 'Especial'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Régimen de afiliación'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipoUsuario',
            field=models.CharField(blank=True, choices=[('C', 'Cotizante'), ('B', 'Beneficiario')], max_length=1, null=True, verbose_name='Tipo de Usuario (RIPS)'),
        ),
    ]
