# Generated by Django 3.2.25 on 2025-08-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20250824_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='regimen',
            field=models.CharField(blank=True, choices=[('CO', 'Contributivo'), ('SU', 'Subsidiado'), ('ES', 'Especial'), ('OT', 'Otro')], max_length=2, null=True, verbose_name='Régimen de afiliación'),
        ),
    ]
