# Generated by Django 3.2.25 on 2025-08-12 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_admision', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('admitido', 'Admitido'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('numero_control', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('contributivo', 'Contributivo'), ('subsidiado', 'Subsidiado'), ('particular', 'Particular'), ('otro', 'Otro')], default='particular', max_length=20)),
                ('entidad_responsable', models.CharField(blank=True, help_text='Nombre de EPS o entidad que autoriza', max_length=100, null=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('remitido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnostico_presuntivo', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
