# Generated by Django 3.2.25 on 2025-08-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admision',
            name='tipo_usuario',
        ),
    ]
