# Generated by Django 3.2.25 on 2025-08-12 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarifas', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('admisiones', '0001_initial'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('enfermedad_actual', models.TextField(blank=True, null=True)),
                ('antecedentes_personales', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares', models.TextField(blank=True, null=True)),
                ('antecedentes_medicos', models.TextField(blank=True, null=True)),
                ('antecedentes_quirurgicos', models.TextField(blank=True, null=True)),
                ('antecedentes_oftalmologicos', models.TextField(blank=True, null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, null=True)),
                ('alergias', models.CharField(blank=True, max_length=255, null=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tensión arterial')),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frecuencia cardíaca')),
                ('av_sin_correccion_od', models.CharField(blank=True, max_length=50, null=True, verbose_name='AV sin corrección OD')),
                ('av_sin_correccion_oi', models.CharField(blank=True, max_length=50, null=True, verbose_name='AV sin corrección OI')),
                ('av_con_correccion_od', models.CharField(blank=True, max_length=50, null=True, verbose_name='AV con corrección OD')),
                ('av_con_correccion_oi', models.CharField(blank=True, max_length=50, null=True, verbose_name='AV con corrección OI')),
                ('av_estenopeico_od', models.CharField(blank=True, max_length=50, null=True, verbose_name='AV estenopeico OD')),
                ('av_estenopeico_oi', models.CharField(blank=True, max_length=50, null=True, verbose_name='AV estenopeico OI')),
                ('refraccion_subjetiva_od', models.CharField(blank=True, max_length=100, null=True, verbose_name='Refracción subjetiva OD')),
                ('refraccion_subjetiva_oi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Refracción subjetiva OI')),
                ('refraccion_objetiva_od', models.CharField(blank=True, max_length=100, null=True, verbose_name='Refracción objetiva OD')),
                ('refraccion_objetiva_oi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Refracción objetiva OI')),
                ('refraccion_final_od', models.CharField(blank=True, max_length=100, null=True, verbose_name='Refracción final OD')),
                ('refraccion_final_oi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Refracción final OI')),
                ('anexos_oculares', models.TextField(blank=True, null=True)),
                ('segmento_anterior', models.TextField(blank=True, null=True)),
                ('segmento_posterior', models.TextField(blank=True, null=True)),
                ('pupilas', models.TextField(blank=True, null=True)),
                ('motilidad_ocular', models.TextField(blank=True, null=True)),
                ('reflejos_pupilares', models.TextField(blank=True, null=True)),
                ('fondo_de_ojo', models.TextField(blank=True, null=True)),
                ('presion_intraocular_od', models.CharField(blank=True, max_length=10, null=True, verbose_name='Presión intraocular OD')),
                ('presion_intraocular_oi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Presión intraocular OI')),
                ('campimetria_visual', models.TextField(blank=True, null=True)),
                ('vision_colores', models.TextField(blank=True, null=True, verbose_name='Test de Ishihara')),
                ('estereopsis', models.TextField(blank=True, null=True)),
                ('diagnostico_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Diagnóstico principal')),
                ('diagnostico_secundario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Diagnóstico secundario')),
                ('cie10_principal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código CIE10 principal')),
                ('plan_tratamiento', models.TextField(blank=True, null=True)),
                ('conducta', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('firmado_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del profesional')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
                ('registro_medico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro Médico (RM)')),
                ('firma_digital', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('admision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='admisiones.admision')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('diagnosticos_cie10', models.ManyToManyField(blank=True, related_name='historias', to='tarifas.Cie10', verbose_name='Diagnósticos adicionales CIE10')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
