# Generated by Django 3.2.25 on 2025-08-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('autorizacion', 'Autorización'), ('orden', 'Orden médica'), ('examen', 'Examen'), ('otro', 'Otro')], max_length=50)),
                ('archivo', models.FileField(upload_to='soportes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
