# Generated by Django 3.2.25 on 2025-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soporte',
            options={'ordering': ['-fecha_carga'], 'verbose_name': 'Soporte', 'verbose_name_plural': 'Soportes'},
        ),
        migrations.AlterField(
            model_name='soporte',
            name='tipo',
            field=models.CharField(choices=[('factura', 'Factura'), ('admisión', 'Admisión'), ('historia', 'Historia clínica'), ('autorizacion', 'Autorización'), ('orden', 'Orden médica'), ('examen', 'Examen'), ('otro', 'Otro')], max_length=50),
        ),
    ]
