# Generated by Django 3.2.25 on 2025-08-27 00:11

from django.db import migrations, models
import soportes.models


class Migration(migrations.Migration):

    dependencies = [
        ('soportes', '0002_auto_20250821_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='archivo',
            field=models.FileField(help_text='Archivo PDF o imagen del soporte.', upload_to=soportes.models.Soporte.ruta_soporte),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción adicional del soporte.', null=True),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='numero_control',
            field=models.CharField(db_index=True, help_text='Número de control interno que agrupa todos los soportes.', max_length=20),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='tipo',
            field=models.CharField(choices=[('factura', 'Factura'), ('admision', 'Admisión'), ('historia', 'Historia clínica'), ('autorizacion', 'Autorización'), ('orden', 'Orden médica'), ('examen', 'Examen'), ('otro', 'Otro')], help_text='Tipo de documento asociado al número de control.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='soporte',
            index=models.Index(fields=['numero_control'], name='soportes_so_numero__042368_idx'),
        ),
    ]
